#!/usr/bin/env python

from time import sleep
from daemonize import Daemonize
import os
import sys
import logging

app = "timerd"
pdir = os.path.join('/tmp', app) 
pid = os.path.join(pdir, "%s.pid" % app)
terminate = False

logger = logging.getLogger(app)
logger.setLevel(logging.DEBUG)
logger.propagate = False
logfile = logging.FileHandler("/var/log/%s.log" % app, "w")
logfile.setLevel(logging.DEBUG)
logger.addHandler(logfile)

keep_fds = [logfile.stream.fileno()]

def main():
    while not terminate:
        sleep(5)

daemon = Daemonize(app=app, pid=pid, action=main, keep_fds=keep_fds)
daemon.start()
